// Mocks generated by Mockito 5.0.17 from annotations
// in muvver_app/test/modules/traveler/domain/usecases/add_traveler_test.dart.
// Do not manually edit this file.

import 'package:mockito/mockito.dart' as _i1;
import 'package:muvver_app/modules/traveler/domain/repositories/add_traveler_repository.dart'
    as _i2;
import 'package:muvver_app/modules/traveler/domain/unities/traveler.dart'
    as _i3;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [AddTravelerRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddTravelerRepository extends _i1.Mock
    implements _i2.AddTravelerRepository {
  MockAddTravelerRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void add(_i3.Traveler? traveler) =>
      super.noSuchMethod(Invocation.method(#add, [traveler]),
          returnValueForMissingStub: null);
}
