// Mocks generated by Mockito 5.0.17 from annotations
// in muvver_app/test/modules/traveler/infra/repositories/add_traveler_repository_impl_test.dart.
// Do not manually edit this file.

import 'package:mockito/mockito.dart' as _i1;
import 'package:muvver_app/modules/traveler/infra/datasources/add_travaler_datasource.dart'
    as _i2;
import 'package:muvver_app/modules/traveler/infra/models/traveler_model.dart'
    as _i3;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [AddTravelerDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddTravelerDatasource extends _i1.Mock
    implements _i2.AddTravelerDatasource {
  MockAddTravelerDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void add(_i3.TravelerModel? traveler) =>
      super.noSuchMethod(Invocation.method(#add, [traveler]),
          returnValueForMissingStub: null);
}
